name: CI
on:
  push:
    branches:
      - 'main'
      - 'development'
  pull_request:
    branches:
      - 'main'
      - 'development'
  workflow_dispatch:
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
          cache: 'npm'

      - name: build
        run: |
          npm cache clean --force
          npm set registry https://registry.npmjs.org/
          npm i
          npm test -- --coverage=true
          npm run build
